# -*- coding: utf-8 -*-
"""lab3numpymethod.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l-OPOQAdUgdfm5iZgToftFES2jtXtdXX
"""

import numpy as np
import random

#1
'''Z = np.zeros((10))
Z[4] = 1
print("1.", Z)'''

#2
'''Z = np.ones((10))
print("2.Вектор одиниць:", Z)'''

#3
'''Z = np.full(10, 2)
print("3.", Z)'''

#4
'''Z = np.arange(10,50)
print("4.",Z)'''

#5
'''Z = np.arange(50)
Z = Z[::-1] #крок -1
print("5.",Z)'''

#6
'''Z = np.arange(25).reshape(5,5) #матриця 5*5, 25 чисел(0,24)
print("6.",Z)'''

#7
'''Z = np.nonzero([1,2,0,0,4,0]) #знаходить індекси ненульових елементів
print(Z)'''

#8
'''Z = np.eye(5) #створює одиничну матрицю 5*5
print(Z)'''

#9
'''Z = np.random.random((3,3,3)) #масив 3*3*3 з випадковими значеннями
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print(Zmin, Zmax)'''

#10
'''Z=np.random.random(20)
z1=Z.mean() #знаходить середнє значення 20 рандомних елементів
Z.sort()
print(Z)
print(z1)'''

#11
'''Z = np.diag(np.arange(1, 5),k=-2) # k - відступ, 2 рядка нульових
print(Z)'''

#12
'''Z = np.tile(np.array([[0,1],[1,0]]), (4,3)) #перше число(в даному випадку 4) множиться на два - рядки, останнэ число (3) - стовпці
print(Z)'''

#13
'''z1=np.ones((5,3)) #множення матриць
z2=np.ones((3,2))
Z = np.dot(z1, z2)
print(z1)
print(z2)
print(Z)'''

#14
'''A = np.random.randint(0,2,5) # від 0 до 2, 5 елементів
B = np.random.randint(0,2,5)
equal = np.allclose(A,B) #провіряє рівні масиви чи ні
print(equal)

K = np.arange(2,5) #вектор [2,3,4]
C = np.full(2,5)
equal = np.allclose(A,B) #провіряє рівні вектори чи ні
print(K)
print(equal)'''

#15
'''a = np.arange(15).reshape(3, 5) #числа від 0 до 14, 3 рядки, 5 стовпців
print(a)
print(a.ndim) #к-сть осей
print(a.shape) #розмір масиву
print(a.size) #к-сть елементів у масиві
print(a.dtype) #описує тип елемента у масиві
print(a.itemsize) #розмір в байтах кожного елемента масива
print(a.data) #буфер, який зберігає фактичні елементи масиву'''

#16
'''a = np.floor(20*np.random.random((3,4)))
print(a)'''